# Generated by Django 6.0.5 on 2026-05-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='skills_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
