# Generated by Django 6.0.5 on 2026-05-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_application_skills_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='application',
            name='candidate_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
