# Generated by Django 6.0.5 on 2026-05-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_application_skills_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
